### ISSUE TITLE
Error build on CentOS 7x64

### ISSUE THREAD

**Issue by nsbelov** [SpiderLabs/ModSecurity-Python-bindings#10]
]# make
swig -I/root/testet/ModSecurity/headers/ -python -builtin -Wall -Wextra -c++ modsecurity/modsecurity.i
/usr/share/swig/2.0.10/std/std_sstream.i:55: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:58: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:95: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:98: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:134: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:174: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:177: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:95: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:98: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:134: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:174: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:177: Warning 321: 'str' conflicts with a built-in name in python
/root/testet/ModSecurity/headers/modsecurity/collection/collection.h:51: Warning 314: 'del' is a python keyword, renaming to '_del'
/root/testet/ModSecurity/headers/modsecurity/collection/collection.h:84: Warning 314: 'del' is a python keyword, renaming to '_del'
/root/testet/ModSecurity/headers/modsecurity/transaction.h:77: Error: Syntax error in input(1).
make: *** [all] Error 1

ModSecurity intsalled with https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes#centos-7-minimal

**Comment by Rue1983** [comment]
Same error happened, is there a plan to update the binding to adopt new version of modsecurity?

**Comment by zimmerle** [comment]
closing in favor of #13
