### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by mmfjunior1** [SpiderLabs/ModSecurity-Python-bindings#11]
Hi!
I have a ubuntu Server with modsecurity 2.9.
I tryed to run the make command in ModSecurity-Python-bindings. The following errors ocurred:
swig -I/usr/local/modsecurity/include/ -python -builtin -Wall -Wextra -c++ modsecurity/modsecurity.i
modsecurity/modsecurity.i:62: Error: Unable to find 'modsecurity/intervention.h'
modsecurity/modsecurity.i:63: Error: Unable to find 'modsecurity/collection/variable.h'
modsecurity/modsecurity.i:64: Error: Unable to find 'modsecurity/collection/collection.h'
modsecurity/modsecurity.i:65: Error: Unable to find 'modsecurity/collection/collections.h'
modsecurity/modsecurity.i:66: Error: Unable to find 'modsecurity/transaction.h'
modsecurity/modsecurity.i:67: Error: Unable to find 'modsecurity/debug_log.h'
modsecurity/modsecurity.i:68: Error: Unable to find 'modsecurity/modsecurity.h'
modsecurity/modsecurity.i:69: Error: Unable to find 'modsecurity/rules_properties.h'
modsecurity/modsecurity.i:70: Error: Unable to find 'modsecurity/rules.h'
modsecurity/modsecurity.i:71: Error: Unable to find 'modsecurity/rule.h'

Can I do anything else?
Thanks!

**Comment by zimmerle** [comment]
Hi @mmfjunior1,

Please make sure you have installed libModSecurity before try to compile the python bindings. The python bindings are specifically looking for ModSecurity headers at: ** /usr/local/modsecurity/include/**
