### ISSUE TITLE
Error while compiling: ‘GlobalVariables’ was not declared in this scope

### ISSUE THREAD

**Issue by kipras** [SpiderLabs/ModSecurity-Python-bindings#7]
When compiling against libmodsecurity https://github.com/SpiderLabs/ModSecurity/tree/1539a8c3efaf51f8109155df9a17e611fb04fd55 i get this error: 

> modsecurity/modsecurity_wrap.cxx: In function ‘int _wrap_new_Collections(PyObject_, PyObject_)’:
> modsecurity/modsecurity_wrap.cxx:15036:3: error: ‘GlobalVariables’ was not declared in this scope
>    GlobalVariables *arg1 = (GlobalVariables *) 0 ;
>    ^
> modsecurity/modsecurity_wrap.cxx:15036:3: note: suggested alternative:
> In file included from /usr/local/modsecurity/include/modsecurity/transaction/collections.h:30:0,
>                  from modsecurity/modsecurity_wrap.cxx:4466:
> /usr/local/modsecurity/include/modsecurity/transaction/global_variables.h:86:7: note:   ‘modsecurity::transaction::GlobalVariables’
>  class GlobalVariables :
>        ^

**Comment by zimmerle** [comment]
Hi @kipras,

What is your version for:
- Python
- Swig
- gcc

**Comment by kipras** [comment]
Hey,

Python 2.7.6
SWIG Version 2.0.11
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

Note, that after replacing `GlobalVariables` with `modsecurity::transaction::GlobalVariables` in `modsecurity/modsecurity_wrap.cxx` - modsecurity binding compiled successfully using `python setup.py build_ext --inplace`.

And the only function that was broken was the `_wrap_new_Collections()` function, other functions already used `modsecurity::transaction::GlobalVariables`.

**Comment by zimmerle** [comment]
closing in favor of #13
