### ISSUE TITLE
Error building on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity-Python-bindings#9]
SWIG: 3.0 (also tried 2.0)
Python: 2.7 (also tried 3.5)

Running `make` I get some errors like:

`modsecurity/modsecurity_wrap.cxx:23432:12: error: use of deleted function 'std::__cxx11::basic_ostringstream<_CharT, _Traits, _Alloc>& std::__cxx11::basic_ostringstream<_CharT, _Traits, _Alloc>::operator=(const std::__cxx11::basic_ostringstream<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]'`

I didn't find what else is missing, or if the python bindings are currently not buildable.

**Comment by Rue1983** [comment]
Also failed like below:

/usr/share/swig/2.0.10/std/std_sstream.i:55: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:58: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:95: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:98: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:134: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:174: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:177: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:95: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:98: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:134: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:174: Warning 321: 'str' conflicts with a built-in name in python
/usr/share/swig/2.0.10/std/std_sstream.i:177: Warning 321: 'str' conflicts with a built-in name in python
/usr/local/modsecurity/include/modsecurity/collection/collection.h:54: Warning 314: 'del' is a python keyword, renaming to '_del'
/usr/local/modsecurity/include/modsecurity/collection/collection.h:117: Warning 314: 'del' is a python keyword, renaming to '_del'
/usr/local/modsecurity/include/modsecurity/collection/collection.h:124: Warning 314: 'del' is a python keyword, renaming to '_del'
/usr/local/modsecurity/include/modsecurity/transaction.h:82: Error: Syntax error in input(1).

**Comment by zimmerle** [comment]
closing in favor of #13
